services:
  api:
    build: .
    container_name: gestor_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:             #ESCALADO VERTICAL (Dar mas recursos al contenedor, no mas instancias)
          cpus: "2.0"       # hasta 2 cores
          memory: 1024M     # hasta 1 GB RAM
        reservations:
          cpus: "1.0"       # pide al menos 1 core
          memory: 512M      # pide al menos 512 MB RAM

  db:
    image: postgres:14
    container_name: gestor_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:             #ESCALADO VERTICAL (Dar mas recursos al contenedor, no mas instancias)
          cpus: "1.0"       # hasta 1 core
          memory: 512M      # hasta 512 MB RAM
        reservations:
          cpus: "0.5"       # pide al menos medio core
          memory: 256M      # pide al menos 256 MB RAM

volumes:
  pgdata: