services:
  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator
    ports:
      - "${ORCHESTRATOR_PORT:-3000}:${ORCHESTRATOR_PORT:-3000}"
    environment:
      PORT: ${ORCHESTRATOR_PORT:-3000}
      AUTH_SERVICE_URL: http://auth-service:${AUTH_SERVICE_PORT:-3001}
      USER_SERVICE_URL: http://user-service:${USER_SERVICE_PORT:-3002}
      PROJECT_SERVICE_URL: http://project-service:${PROJECT_SERVICE_PORT:-3003}
      TASK_SERVICE_URL: http://task-service:${TASK_SERVICE_PORT:-3004}
    depends_on:
      - auth-service
      - user-service
      - project-service
      - task-service

  auth-service:
    build:
      context: ./services/auth
    container_name: auth-service
    environment:
      PORT: ${AUTH_SERVICE_PORT:-3001}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET:-mi_secreto_jwt_super_seguro_cambialo_en_produccion}
    depends_on:
      - db

  user-service:
    build:
      context: ./services/user
    container_name: user-service
    environment:
      PORT: ${USER_SERVICE_PORT:-3002}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  project-service:
    build:
      context: ./services/project
    container_name: project-service
    environment:
      PORT: ${PROJECT_SERVICE_PORT:-3003}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  task-service:
    build:
      context: ./services/task
    container_name: task-service
    environment:
      PORT: ${TASK_SERVICE_PORT:-3004}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gestor_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
