FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Puerto por defecto (puede ser sobrescrito por variable de entorno en runtime)
ENV PORT=3002
EXPOSE $PORT

CMD ["node", "dist/userService.js"]
